version: "3.9"
services:
  db:
    image: ankane/pgvector:latest
    container_name: ai-interview-coach-db
    environment:
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai_pass
      - POSTGRES_DB=ai_interview
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai -d ai_interview"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    container_name: ai-interview-coach-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      # data 폴더는 더 이상 사용하지 않음 (SQLite/Chroma 제거)
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  worker:
    build: .
    container_name: ai-interview-coach-worker
    command: ["python", "-m", "app.worker.main"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./frontend
    container_name: ai-interview-coach-web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
